version: "3.5"
services:
  backend:
    container_name: api
    build: ./backend/
    ports:
      - 4000:4000
  frontend:
    container_name: web
    build: ./frontend/relish/
    ports:
      - 3000:3000